name: BuildTests
permissions:
  contents: read
on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20, 22, 24]
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
          node-version: "${{ matrix.node-version }}"

      - name: allow write in work dir
        run: sudo chmod -R 777 .

      - name: Install Dependencies
        run: |
          pnpm install

      - name: Building niconicomments
        run: pnpm build
